apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apachewebsite
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apachewebsite
  template:
    metadata:
      labels:
        app: apachewebsite
    spec:
      containers:
      - name: apache-container
        image: rohith252/apachewebsite:latest
        ports:
        - containerPort: 80
